env:
  python_bin: "python" # Path to the python bin
  base_project_dir: ${hydra:runtime.cwd}
  before_train_commands: []
  torch_extensions_dir: "/tmp/torch_extensions"
  datasets_dir: "data"
  objects_to_copy:
    - ${env.base_project_dir}/src
    - ${env.base_project_dir}/configs
  # A list of objects that are static and too big
  # to be copy-pasted for each experiment
  symlinks_to_create:
    - ${env.base_project_dir}/data
num_gpus: 4
dataset:
  source_path: /ibex/scratch/projects/c2112/datasets/zip-data-links/${dataset.name}.zip
  target_path: /tmp/datasets/${dataset.name}.zip
print_only: false

project_release_dir:
  _target_: infra.utils.get_experiment_path
  # master_dir: /ibex/scratch/skoroki/sgf/experiments
  master_dir: /ibex/scratch/projects/c2112/new-sgf-experiments
  experiment_name: ${experiment_name}

training_cmd_cli_args:
  outdir: ${project_release_dir}
  data: ${dataset.target_path}
  gpus: ${num_gpus}
  cfg: auto
  g_fmaps: 0.5
  d_fmaps: 0.5
  snap: 100

  # Let's by default have only x flips
  aug: noaug
  mirror: 1
  z_dim: 512
  w_dim: 512

  # By default, use ALIS config
  hydra_cfg_name: "alis.yml"

training_cmd_cli_args_str:
  _target_: infra.utils.cfg_to_args_str
  cfg: ${training_cmd_cli_args}
